### ISSUE TITLE
مشکل دریافت تاریخچه سهام جابه جا شده 

### ISSUE THREAD

**Issue by noktebin** [yghaderi/metafid-data#1]
سهامی که بین بازارهای مختلف جابه جا شده است در هنگام دریافت تاریخچه فقط آخرین روزهایی که در بازار جدید بوده دریافت میشود.
به عنوان نمونه سهم دی پس از جابه جایی از بورس به بازار پایه با اجرای کد زیر فقط تاریخچه معاملات بازار پایه بازگردانده میشود.

hist_data = tsetmc.adj_hist_price(symbol = 'دی')

print (hist_data)
         date           ins_code    open  ...  adj_low  adj_close  adj_final
0  2023-12-16  66416853783916493     0.0  ...      0.0     1000.0     1000.0
1  2023-12-18  66416853783916493     0.0  ...      0.0     1000.0     1000.0
2  2023-12-19  66416853783916493     0.0  ...      0.0     1000.0     1000.0
...
47 2024-02-21  66416853783916493     0.0  ...      0.0     1119.0     1118.0
48 2024-02-24  66416853783916493     0.0  ...      0.0     1119.0     1118.0
[49 rows x 16 columns]

**Comment by yghaderi** [comment]
سلام. 
در ورژن جدید حل شد، البته با راه-حلِ سریع که در آینده بهتر میشه. 
from oxtapus import TSETMC
tsetmc = TSETMC(get_all_ins_code=True)

با True کردنِ get_all_ins_code میتونی نمادهای حذف شده رو هم بگیری.

tsetmc.adj_hist_price(symbol= "دی")
shape: (3_095, 16)
┌────────────┬───────────────────┬────────┬────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ date       ┆ ins_code          ┆ open   ┆ high   ┆ … ┆ adj_high ┆ adj_low ┆ adj_close ┆ adj_final │
│ ---        ┆ ---               ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---     ┆ ---       ┆ ---       │
│ date       ┆ str               ┆ f64    ┆ f64    ┆   ┆ f64      ┆ f64     ┆ f64       ┆ f64       │
╞════════════╪═══════════════════╪════════╪════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 2023-12-16 ┆ 66416853783916493 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1000.0    ┆ 1000.0    │
│ 2023-12-18 ┆ 66416853783916493 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1000.0    ┆ 1000.0    │
│ 2023-12-19 ┆ 66416853783916493 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1000.0    ┆ 1000.0    │
│ 2023-12-20 ┆ 66416853783916493 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1000.0    ┆ 1000.0    │
│ 2023-12-23 ┆ 66416853783916493 ┆ 1089.0 ┆ 1119.0 ┆ … ┆ 1119.0   ┆ 1057.0  ┆ 1064.0    ┆ 1068.0    │
│ …          ┆ …                 ┆ …      ┆ …      ┆ … ┆ …        ┆ …       ┆ …         ┆ …         │
│ 2023-12-06 ┆ 44818950263583523 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1057.0    ┆ 1057.0    │
│ 2023-12-09 ┆ 44818950263583523 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1057.0    ┆ 1057.0    │
│ 2023-12-10 ┆ 44818950263583523 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1057.0    ┆ 1057.0    │
│ 2023-12-11 ┆ 44818950263583523 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1057.0    ┆ 1057.0    │
│ 2023-12-12 ┆ 44818950263583523 ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0      ┆ 0.0     ┆ 1057.0    ┆ 1057.0    │
└────────────┴───────────────────┴────────┴────────┴───┴──────────┴─────────┴───────────┴───────────┘


ممنون بابت اطلاع

**Comment by noktebin** [comment]
سلام.
فوق العاده سریع و خوب.
