### ISSUE TITLE
عدم وجود دیتای حقیقی و حقوقی در خروجی mw

### ISSUE THREAD

**Issue by noktebin** [yghaderi/metafid-data#2]
با سلام و  تشکر از کتابخانه خوبتون

دیتای حقیقی و حقوقی در خروجی تابع mw وجود نداره با وجود اینکه در همان صفحه مارکت واچ این دیتا با یک وبسرویس برای همه سهم ها موجوده. علتی داره که این کار رو نکردید؟

**Comment by yghaderi** [comment]
سلام
در ورژنِ 0.3.1 اضافه شد.
