### ISSUE TITLE
اضافه کردن میانگین حجم ماه به کتابخانه

### ISSUE THREAD

**Issue by SinaSarvi** [yghaderi/metafid-data#3]
با سلام و وقت بخیر

سپاس از زحمتی که کشیدین.

اگر تمام دیتایی که در صفحه اختیار هر نماد وجود داره رو دریافت کنین و در پانداس ذخیره بشه، این کتابخونه بسیار کاربردی‌تر می‌شه.

مواردی مثل میانگین حجم ماه آپشن و دیتای مربوط به خرید حقیقی و حقوقی هر نماد آپشن منظورم هست.

**Comment by yghaderi** [comment]
سلام، ممنون

با متدِ ins_info میتونید داده‌یِ میانگینِ حجمِ ماه رو بگیری و حقیقی-حقوقی رو هم  با متدِ client_type .
