### ISSUE TITLE
دریافت دیتای اختیار فرابورس از سایت بورس

### ISSUE THREAD

**Issue by noktebin** [yghaderi/metafid-data#5]
به نظر صفحه دیده بان اختیار سایت بورس به روز رسانی داده و دیتای فرابورس رو هم نمایش میده. میتونید متدهای دریافت دیتای اختیار رو یکی کنید. و کلش رو با یک متد از بورس بخونید.

**Comment by yghaderi** [comment]
سلام.
داده‌یِ اختیار این دو بازار جدا از همه.  ممکنه برخی‌ها علاقه‌مند به پرداختِ هزینه‌یِ درخواست دو بازار نباشن. البته می‌شد به عنوان پارامتر ورودی بازار هم انتخاب بشه، ولی چون به راحتی توسط بهره-گیر قابلِ حله، جداشون کردم. 

```
import polars as pl
from oxtapus import TSETMC

def omw():
    tsetmc = TSETMC()
    tse_omw = tsetmc.tse_options_mw().with_columns(pl.lit("tse").alias("market"))
    ifb_omw=tsetmc.ifb_options_mw().with_columns(pl.lit("ifb").alias("market"))
    return pl.concat([tse_omw, ifb_omw])
```
